### ISSUE TITLE
Can I have Tanaguru and Jenkins on same machine

### ISSUE THREAD

**Issue by softwareklinic** [Tanaguru/jenkins-tanaguru-plugin#5]
Hi For testing purpose can i have Jenkins, Tanaguru-cli, and tanaguru web on same machine... on same mysql??

**Comment by fhalna** [comment]
hi,
yes you can all install on the same server and on the same mysql.

For your information the plugin Jenkins is fully operational. It's used by several french public companies and different providers of technology.

**Comment by softwareklinic** [comment]
Do I need 2 different xvfb configs - 1 for tanaguru web and other for tanaguru cli?

Regards,
Keyur

On Feb 10, 2016, at 5:51 AM, halna <notifications@github.com<mailto:notifications@github.com>> wrote:

hi,
yes you can all install on the same server and on the same mysql.

For your information the plugin Jenkins is fully operational. It's used by several french public companies and different providers of technology.

**Comment by mkebri** [comment]
Hi, 
You can use the same configuration for both (web and CLI), its not necessary to have two different xvfb configs.

Regards.

**Comment by softwareklinic** [comment]
Ty

Regards,
Keyur

On Feb 10, 2016, at 6:33 AM, KEBRI Mustapha <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
You can use the same configuration for both (web and CLI), its not necessary to have two different xvfb configs.

Regards.

**Comment by softwareklinic** [comment]
One more question -related --- can i have Tanaguru CLI on separate machine than Jenkins.. since i don't want the jenkins server to take load...

**Comment by mkebri** [comment]
No we must have the both (cli,  Jenkins ) in the same machine.

Regards

**Comment by softwareklinic** [comment]
Is the cli very resource intensive

Regards,
Keyur

On Feb 10, 2016, at 10:02 AM, KEBRI Mustapha <notifications@github.com<mailto:notifications@github.com>> wrote:

No we must have the both (cli, Jenkins ) in the same machine.

Regards

**Comment by fhalna** [comment]
not really, there is a queue to limit parallel traitement

**Comment by softwareklinic** [comment]
Ty

Regards,
Keyur

On Feb 10, 2016, at 10:59 AM, halna <notifications@github.com<mailto:notifications@github.com>> wrote:

not really, there is a queue to limit parallel traitement

**Comment by softwareklinic** [comment]
Can u help me
Look at the other
Issue related to cli testing before I use it in Jenkins

Regards,
Keyur

On Feb 10, 2016, at 10:59 AM, halna <notifications@github.com<mailto:notifications@github.com>> wrote:

not really, there is a queue to limit parallel traitement
