### ISSUE TITLE
Tanaguru - CLI - error

### ISSUE THREAD

**Issue by softwareklinic** [Tanaguru/jenkins-tanaguru-plugin#6]
Hi 

When trying to run the tanaguru.sh with a URL in terminal - it launches a new firefox window - but doesnt navigate to that url and then it fails with below error after few seconds

```
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
... 36 more
```

crash (id+message): 8 org.tanaguru.scenarioloader.exception.ScenarioLoaderException: java.lang.RuntimeException: Test run failed: unable to create driver.

I have xvfb installed/started - at 99 screen 1... and firefox installed as recommended in the installation/prerequisite steps

**Comment by mkebri** [comment]
what was the cammand you have used to run the tanaguru.sh ?

**Comment by softwareklinic** [comment]
Was in the tanaguru.xx.x.. Folder and ran

Tanagura.xxx.xxx.> $ ./bin/tanaguru.sh http://www.google.com

**Comment by mkebri** [comment]
Try with this command: 
./bin/tanaguru.sh -d 99 -f /pathToTheBinaryOfInstaledFirefoxeFortanaguru/firefox-esr/firefox http://www.google.com

Options:  
-d : the dispaly port of the xvfb as set in the configuration steps
-f : the path to the binary of firefox esr(recomanded in the steps installation) don't use an other version (as newer)

**Comment by softwareklinic** [comment]
it worked... thank youl.. now i will goto next level - to trigger this from jenkins.. but another question....

can these tests show up in the tanaguru UI??? if i put it as a part of some contract???

**Comment by mkebri** [comment]
In UI of the plugin we specify the name of the contrat under the audits will be created, and we can consult them in the tanaguru UI.
